source 'https://rubygems.org'
ruby '2.1.1'

group :development do
  gem 'foreman'

  # Sass, Compass and extensions.
  gem 'sass'                    # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass'                 # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
  gem 'breakpoint'              # Really simple, organized, media queries with sass
  gem 'singularitygs'           # Alternative to the Susy grid framework.
  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.
end
